# Module manifest for module 'MSGraphPSEssentials'
# Generated by: Jeremy Bradshaw
# Generated on: TBD

@{
    RootModule           = 'MSGraphPSEssentials.psm1'
    ModuleVersion        = '0.1.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID                 = '7394f3f8-a172-4e18-8e40-e41295131e0b'
    Author               = 'Jeremy.Bradshaw@Outlook.com'
    CompanyName          = ''
    Copyright            = '(c) 2020 Jeremy Bradshaw. All rights reserved.'
    Description          = 'A collection of functions enabling easier consumption of Microsoft Graph using just PowerShell (Desktop/Core).'
    PowerShellVersion    = '5.1'
    FunctionsToExport    = @(
        'New-MSGraphAccessToken',
        'New-MSGraphRequest',
        'New-SelfSignedMSGraphApplicationCertificate',
        'New-MSGraphPoPToken',
        'Add-MSGraphApplicationKeyCredential',
        'Remove-MSGraphApplicationKeyCredential',
        'Test-SigningCertificate',
        'ConvertTo-Base64Url',
        'ConvertFrom-Base64Url',
        'ConvertFrom-JWTAccessToken',
        'New-TokenCredential'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @('New-SelfSignedAzureADAppRegistrationCertificate')
    PrivateData          = @{

        PSData = @{
            Tags         = @('MicrosoftGraph', 'OAuth', 'App-Only', 'Delegated', 'DeviceCode', 'JWT', 'AccessToken', 'RefreshToken')
            LicenseUri   = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials'
            ReleaseNotes = @'
v0.1.1 - (unpublished as of 2020-12-31):

    - Fixed missing ')' in the Device Code choice prompt caption.
    - Added function: New-TokenCredential
'@
        }
    }
    HelpInfoURI          = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/README.md'
}
