#
# Module manifest for module 'MSGraphPSEssentials'
#
# Generated by: Jeremy Bradshaw
#
# Generated on: 12/05/2020
#

@{
    RootModule           = 'MSGraphPSEssentials.psm1'
    ModuleVersion        = '0.0.0'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID                 = '7394f3f8-a172-4e18-8e40-e41295131e0b'
    Author               = 'Jeremy.Bradshaw@Outlook.com'
    CompanyName          = ''
    Copyright            = '(c) 2020 Jeremy Bradshaw. All rights reserved.'
    Description          = 'Description TBD'
    PowerShellVersion    = '5.1'
    FunctionsToExport    = @()
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{

        PSData = @{
            Prerelease   = 'pre-alpha'
            Tags         = @('Microsoft Graph', 'OAuth', 'App-Only', 'Delegated', 'Device Code', 'JWT', 'Access Token', 'Refresh Token')
            LicenseUri   = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials'
            ReleaseNotes = @'
    
v0.0.0 (2020-12-05):

  - Initial prerelease / pre-alpha version.
'@
        }
    }
    HelpInfoURI          = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/README.md'
}
