# Module manifest for module 'MSGraphPSEssentials'
# Generated by: Jeremy Bradshaw
# Generated on: 2021-04-21

@{
    RootModule           = 'MSGraphPSEssentials.psm1'
    ModuleVersion        = '0.3.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID                 = '7394f3f8-a172-4e18-8e40-e41295131e0b'
    Author               = 'Jeremy.Bradshaw@Outlook.com'
    CompanyName          = ''
    Copyright            = '(c) 2020 Jeremy Bradshaw. All rights reserved.'
    Description          = 'A collection of functions enabling easier consumption of Microsoft Graph using just PowerShell (Desktop/Core).'
    PowerShellVersion    = '5.1'
    FunctionsToExport    = @(
        'New-MSGraphAccessToken',
        'New-MSGraphRequest',
        'New-SelfSignedMSGraphApplicationCertificate',
        'New-MSGraphPoPToken',
        'Add-MSGraphApplicationKeyCredential',
        'Remove-MSGraphApplicationKeyCredential',
        'ConvertFrom-JWTAccessToken',
        'New-RefreshTokenCredential'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @('New-SelfSignedAzureADAppRegistrationCertificate')
    PrivateData          = @{

        PSData = @{
            Tags         = @('MicrosoftGraph', 'OAuth', 'App-Only', 'Delegated', 'DeviceCode', 'JWT', 'AccessToken', 'RefreshToken')
            LicenseUri   = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials'
            ReleaseNotes = @'
v0.3.1 (2021-04-21):

- Fixed 3 instances of same typo ('throw = ' (dropped the '=').
- Fixed New-SelfSignedMSGraphApplicationCertificate function:
    Implemented crutch-fix for New-SelfSignedCertificate on PS Core to make private key available.
    (related to known issue: https://github.com/PowerShell/PowerShell/issues/12081)
'@
        }
    }
    HelpInfoURI          = 'https://github.com/JeremyTBradshaw/MSGraphPSEssentials/blob/main/README.md'
}
